name: AsyncAPI Validate

on:
  pull_request:
    paths:
      - "asyncapi.yml"
  workflow_dispatch:
  push:
    paths:
      - "asyncapi.yml"

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      #"standard step" where repo needs to be checked-out first
      - name: Checkout repo
        uses: actions/checkout@v3

      #Using another action for AsyncAPI for validation
      - name: Validating AsyncAPI document
        uses: WaleedAshraf/asyncapi-github-action@v0.0.8
        with:
          filepath: asyncapi.yml
