name: Build Docker image

on:
  workflow_dispatch:
  push:
    branches-ignore: [main]
    paths:
      - "server/**"
  pull_request:
    paths:
      - "server/**"

jobs:
  build-image:
    runs-on: ubuntu-latest

    # When the pull request is not from a fork,
    # then the workflow is triggered by "push" and "pull_request"
    # To not run a workflow 2 times, we check if the pull request is from a fork
    if: ${{ github.event_name != 'pull_request' || github.repository_owner != 'Commandcracker' }}

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Build image 🔨
        uses: docker/build-push-action@v3
        with:
          context: server
