name: Pylint

on:
  workflow_dispatch:
  push:
    paths:
      - "server/**.py"
  pull_request:
    paths:
      - "server/**.py"

jobs:
  pylint:
    runs-on: ubuntu-latest

    # When the pull request is not from a fork,
    # then the workflow is triggered by "push" and "pull_request"
    # To not run a workflow 2 times, we check if the pull request is from a fork
    if: ${{ github.event_name != 'pull_request' || github.repository_owner != 'Commandcracker' }}

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Set up Python 🧰
        uses: actions/setup-python@v4
        with:
          python-version: "3"

      - name: Install dependencies 🧰
        run: |
          python -m pip install --upgrade pip
          pip install -r server/requirements.txt
          pip install pylint

      - name: Pylint ✅
        run: |
          pylint $(git ls-files '*.py')
