name: Pylint

on:
  pull_request:
  workflow_dispatch:
  push:

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r server/requirements.txt
          pip install pylint

      - name: Pylint
        run: |
          pylint $(git ls-files '*.py')
