name: Spellcheck
# Currently, only python is spellchecked

on:
  workflow_dispatch:
  push:
    paths:
      - "server/**.py"
  pull_request:
    paths:
      - "server/**.py"

jobs:
  spellcheck:
    runs-on: ubuntu-latest

    # When the pull request is not from a fork,
    # then the workflow is triggered by "push" and "pull_request"
    # To not run a workflow 2 times, we check if the pull request is from a fork
    if: ${{ github.event_name != 'pull_request' || github.repository_owner != 'Commandcracker' }}

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Spellcheck ✅
        uses: rojopolis/spellcheck-github-actions@0.28.0
