name: Spellcheck

on:
  pull_request:
  workflow_dispatch:
  push:

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Spellcheck
        uses: rojopolis/spellcheck-github-actions@0.27.0
